const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.sliderbar,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.scormc2,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.sliderbar.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.scormc2.Acts.initialiseLMS,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.sliderbar.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.sliderbar.Cnds.PickByUID,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Cnds.OnChanged,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.sliderbar.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.lunarray_LiteTween.Acts.Stop,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.scormc2.Acts.setLMSValue,
		C3.Plugins.scormc2.Acts.doLMSCommit,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.sliderbar.Exps.Y,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.sliderbar.Cnds.IsEnabled,
		C3.Plugins.Text.Acts.SetFontColor
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{rightcontent: 0},
	{oldSizeWidth: 0},
	{oldSizeHeight: 0},
	{oldPosX: 0},
	{oldPosY: 0},
	{newPosX: 0},
	{newPosY: 0},
	{groupID: 0},
	{instrumentID: 0},
	{isActive: 0},
	{volumeInstrumentUID: 0},
	{middleAreaUID: 0},
	{volumeGroupUID: 0},
	{melodi: 0},
	{melodi2: 0},
	{melodi3: 0},
	{solo: 0},
	{solo2: 0},
	{solo3: 0},
	{bas: 0},
	{bas2: 0},
	{bas3: 0},
	{ritim: 0},
	{ritim2: 0},
	{ritim3: 0},
	{channelText: 0},
	{SliderBar: 0},
	{SliderBar2: 0},
	{SliderBar3: 0},
	{SliderBar4: 0},
	{instrumentUID: 0},
	{SliderBar5: 0},
	{clicked: 0},
	{play: 0},
	{clear: 0},
	{playMode: 0},
	{slidebarUID: 0},
	{play2: 0},
	{SliderBar6: 0},
	{SliderBar7: 0},
	{SliderBar8: 0},
	{SliderBar9: 0},
	{SliderBar10: 0},
	{SliderBar11: 0},
	{SliderBar12: 0},
	{SliderBar13: 0},
	{SliderBar14: 0},
	{SliderBar15: 0},
	{SliderBar16: 0},
	{play3: 0},
	{play4: 0},
	{play5: 0},
	{play6: 0},
	{play7: 0},
	{play8: 0},
	{play9: 0},
	{play10: 0},
	{play11: 0},
	{play12: 0},
	{play13: 0},
	{LiteTween: 0},
	{playbar: 0},
	{placed: 0},
	{placedInstrumentUID: 0},
	{placedInstrumentID: 0},
	{volumeUID: 0},
	{middleArea: 0},
	{middleArea2: 0},
	{middleArea3: 0},
	{middleArea4: 0},
	{Function: 0},
	{Touch: 0},
	{Audio: 0},
	{Mouse: 0},
	{btnbg: 0},
	{btnbg2: 0},
	{infoBtn: 0},
	{homeBtn: 0},
	{Sprite: 0},
	{context: 0},
	{closeBtn: 0},
	{sourceBtn: 0},
	{infoText: 0},
	{info2Btn: 0},
	{startBtn: 0},
	{logo: 0},
	{sourceText: 0},
	{ScormC2: 0},
	{return: 0},
	{channelText2: 0},
	{volumeHover1: 0},
	{volumeHover2: 0},
	{volumeHover3: 0},
	{volumeHover4: 0},
	{icon: 0},
	{prepareBtn: 0},
	{prepareContent: 0},
	{playInstruments: 0},
	{volumeInstruments: 0},
	{volumeGroups: 0},
	{DragDrop: 0},
	{instruments: 0},
	{middleAreas: 0},
	{btnbgs: 0},
	{volumeHovers: 0},
	{activeMiddleAreaUID: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	rightcontent: class extends self.ISpriteInstance {},
	melodi: class extends self.ISpriteInstance {},
	melodi2: class extends self.ISpriteInstance {},
	melodi3: class extends self.ISpriteInstance {},
	solo: class extends self.ISpriteInstance {},
	solo2: class extends self.ISpriteInstance {},
	solo3: class extends self.ISpriteInstance {},
	bas: class extends self.ISpriteInstance {},
	bas2: class extends self.ISpriteInstance {},
	bas3: class extends self.ISpriteInstance {},
	ritim: class extends self.ISpriteInstance {},
	ritim2: class extends self.ISpriteInstance {},
	ritim3: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	SliderBar2: class extends self.ISliderBarInstance {},
	SliderBar3: class extends self.ISliderBarInstance {},
	SliderBar4: class extends self.ISliderBarInstance {},
	SliderBar5: class extends self.ISliderBarInstance {},
	play: class extends self.ISpriteInstance {},
	clear: class extends self.ISpriteInstance {},
	play2: class extends self.ISpriteInstance {},
	SliderBar6: class extends self.ISliderBarInstance {},
	SliderBar7: class extends self.ISliderBarInstance {},
	SliderBar8: class extends self.ISliderBarInstance {},
	SliderBar9: class extends self.ISliderBarInstance {},
	SliderBar10: class extends self.ISliderBarInstance {},
	SliderBar11: class extends self.ISliderBarInstance {},
	SliderBar12: class extends self.ISliderBarInstance {},
	SliderBar13: class extends self.ISliderBarInstance {},
	SliderBar14: class extends self.ISliderBarInstance {},
	SliderBar15: class extends self.ISliderBarInstance {},
	SliderBar16: class extends self.ISliderBarInstance {},
	play3: class extends self.ISpriteInstance {},
	play4: class extends self.ISpriteInstance {},
	play5: class extends self.ISpriteInstance {},
	play6: class extends self.ISpriteInstance {},
	play7: class extends self.ISpriteInstance {},
	play8: class extends self.ISpriteInstance {},
	play9: class extends self.ISpriteInstance {},
	play10: class extends self.ISpriteInstance {},
	play11: class extends self.ISpriteInstance {},
	play12: class extends self.ISpriteInstance {},
	play13: class extends self.ISpriteInstance {},
	playbar: class extends self.ISpriteInstance {},
	middleArea: class extends self.ISpriteInstance {},
	middleArea2: class extends self.ISpriteInstance {},
	middleArea3: class extends self.ISpriteInstance {},
	middleArea4: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	btnbg: class extends self.ISpriteInstance {},
	btnbg2: class extends self.ISpriteInstance {},
	infoBtn: class extends self.ISpriteInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	context: class extends self.ISpriteInstance {},
	closeBtn: class extends self.ISpriteInstance {},
	sourceBtn: class extends self.ISpriteInstance {},
	infoText: class extends self.ISpriteInstance {},
	info2Btn: class extends self.ISpriteInstance {},
	startBtn: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	sourceText: class extends self.ISpriteInstance {},
	ScormC2: class extends self.IInstance {},
	return: class extends self.ISpriteInstance {},
	channelText2: class extends self.ITextInstance {},
	channelText: class extends self.ITextInstance {},
	volumeHover1: class extends self.ISpriteInstance {},
	volumeHover2: class extends self.ISpriteInstance {},
	volumeHover3: class extends self.ISpriteInstance {},
	volumeHover4: class extends self.ISpriteInstance {},
	icon: class extends self.ISpriteInstance {},
	prepareBtn: class extends self.ISpriteInstance {},
	prepareContent: class extends self.ISpriteInstance {},
	playInstruments: class extends self.ISpriteInstance {},
	volumeInstruments: class extends self.ISliderBarInstance {},
	volumeGroups: class extends self.ISliderBarInstance {},
	instruments: class extends self.ISpriteInstance {},
	middleAreas: class extends self.ISpriteInstance {},
	btnbgs: class extends self.ISpriteInstance {},
	volumeHovers: class extends self.ISpriteInstance {}
}